### PR TITLE
fix: prevent exceeding timer limitations when backing off

### LINKED ISSUE #1167: `TimeoutOverflowWarning`s when stress testing services
### Problem description

With `@grpc/grpc-js` v0.6.11 the following warning can be observed during execution of computationally stressful tasks:

```
(node:28317) TimeoutOverflowWarning: 4294967294 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:28316) TimeoutOverflowWarning: 4294967294 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:28317) TimeoutOverflowWarning: 8589934588 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

### Reproduction steps

From the server side, send a response that triggers this condition: https://github.com/grpc/grpc-node/blob/73a767d14eba04384f0a9e3d1f8079f50c842d34/packages/grpc-js/src/subchannel.ts#L284

### Environment
 - OS name, version and architecture: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
 - Node version: v10.16.3
 - Node installation method: nvm
 - If applicable, compiler version: not relevant
 - Package name and version: @grpc/grpc-js v0.6.11

### Additional context

### PR DESCRIPTION
**Pull request by merlinnot**
Resolves #1167

### CODE REVIEW

File: packages/grpc-js/src/subchannel.ts [hunk 1]
```diff
@@ -283,7 +283,7 @@ export class Subchannel {
          * https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#basic-keepalive */
         if (errorCode === http2.constants.NGHTTP2_ENHANCE_YOUR_CALM && opaqueData.equals(tooManyPingsData)) {
           logging.log(LogVerbosity.ERROR, `Connection to ${this.channelTarget} rejected by server because of excess pings`);
-          this.keepaliveTimeMs *= 2;
+          this.keepaliveTimeMs = Math.min(2 * this.keepaliveTimeMs, KEEPALIVE_TIME_MS);
```
Comment (merlinnot) [inline packages/grpc-js/src/subchannel.ts]: Should we rename this constant to `KEEPALIVE_MAX_TIME_MS`?

Comment (murgatroid99) [reply packages/grpc-js/src/subchannel.ts]: Yes, I guess that makes sense.

Comment (merlinnot) [reply packages/grpc-js/src/subchannel.ts]: Done!
