### PR TITLE
fix: only unref timers in supported environments

### LINKED ISSUE #1077: Uncaught TypeError: setInterval(...).unref is not a function (when called from electron)
### Problem description
I'm getting this error when trying to use `@grpc/grpc-js@0.6.9` from within a web worker running under Electron.

> Uncaught TypeError: setInterval(...).unref is not a function

The same code works ok in grpc-js 5.x version.

### Reproduction steps

Try to use latest release in a node enabled web worker within electron.

### Environment
 - OS name, version and architecture: Mac
 - Node version 12.x
 - Node installation method nvm
 - Package name and version @grpc/grpc-js@0.6.9

### Additional context

```
Uncaught TypeError: setInterval(...).unref is not a function
    at new SubchannelPool (subchannel-pool.js?f8bb:55)
    at eval (subchannel-pool.js?f8bb:99)
    at Object../node_modules/@grpc/grpc-js/build/src/subchannel-pool.js (grpc.worker.js:504)
    at __webpack_require__ (grpc.worker.js:20)
    at eval (channel.js?e974:21)
    at Object../node_modules/@grpc/grpc-js/build/src/channel.js (grpc.worker.js:192)
    at __webpack_require__ (grpc.worker.js:20)
    at eval (index.js?0156:22)
    at Object../node_modules/@grpc/grpc-js/build/src/index.js (grpc.worker.js:276)
    at __webpack_require__ (grpc.worker.js:20)
```

### PR DESCRIPTION
**Pull request by mrfelton**
fix #1077

### CODE REVIEW

**Comment by merlinnot** [comment]
@mrfelton This needs a rebase, my PR touching these files was merged first. Sorry!

**Comment by mrfelton** [comment]
Updated @merlinnot

File: packages/grpc-js/src/subchannel-pool.ts [hunk 1]
```diff
@@ -101,7 +101,7 @@ export class SubchannelPool {
       }, REF_CHECK_INTERVAL);
 
       // Unref because this timer should not keep the event loop running.
-      this.cleanupTimer.unref();
+      this.cleanupTimer.unref && this.cleanupTimer.unref();
```
Comment (murgatroid99) [inline packages/grpc-js/src/subchannel-pool.ts]:
```suggestion
      // Call unref only if it exists to address electron/electron#21162
      this.cleanupTimer.unref?.();
```

I prefer this check, [introduced in Typescript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html). I think it more directly communicates the intention of "call unref if it is present".

This will only work after #1184 is merged, or if this PR also makes the same upgrade of the `typescript` dependency as in that PR.
