### PR TITLE
Fix DNS name regex and add tests

### LINKED ISSUE #1044: Failed to parse target a-b:1234
### Problem description

Not all valid hostnames can be used with `@grpc/grpc-js` v0.6.0, e.g. `a-b`, `a.b` are not considered valid given this RegExp: https://github.com/grpc/grpc-node/blob/e055468c299a1a22cc36b7760175b1964a3067d7/packages/grpc-js/src/resolver-dns.ts#L57

### Reproduction steps

Try to initialize the client with a hostnames like this:
- `firestore-emulator:1234`
- `http://pubsub-emulator:4321`

### Environment
 - OS name, version and architecture: Darwin Kernel Version 19.0.0: Sat Aug 31 18:49:12 PDT 2019; root:xnu-6153.11.15~8/RELEASE_X86_64 x86_64
 - Node version: 10.16.3
 - Node installation method: nvm
 - If applicable, compiler version: Apple clang version 11.0.0 (clang-1100.0.31.5)
 - Package name and version: @grpc/grpc-js@0.6.0

### Additional context

```
Step #3 - "test":     Failed to parse target http://firestore-emulator:4500
Step #3 - "test": 
Step #3 - "test":       38 |     const sslCredentials = credentials.createInsecure();
Step #3 - "test":       39 | 
Step #3 - "test":     > 40 |     const client = new FirestoreEmulator(address, sslCredentials);
Step #3 - "test":          |                    ^
Step #3 - "test":       41 | 
Step #3 - "test":       42 |     return client;
Step #3 - "test":       43 |   },
Step #3 - "test": 
Step #3 - "test":       at Function.getDefaultAuthority (node_modules/@grpc/grpc-js/build/src/resolver-dns.js:242:15)
Step #3 - "test":       at Object.getDefaultAuthority (node_modules/@grpc/grpc-js/build/src/resolver.js:72:32)
Step #3 - "test":       at new ChannelImplementation (node_modules/@grpc/grpc-js/build/src/channel.js:85:48)
Step #3 - "test":       at new Client (node_modules/@grpc/grpc-js/build/src/client.js:37:36)
Step #3 - "test":       at new ServiceClientImpl (node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
Step #3 - "test":       at Object.<anonymous>.exports.myFunctionName (some/path/index.ts:40:20)
```

### PR DESCRIPTION
**Pull request by murgatroid99**
Fixes #1044.

### CODE REVIEW

File: packages/grpc-js/test/test-resolver.ts [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+          done(new Error(`Failed with status ${error.details}`));
+        },
+      };
+      const resolver = resolverManager.createResolver(target, listener);
+      resolver.updateResolution();
+    });
+    it('Should resolve a name with a hyphen', done => {
+      /* TODO(murgatroid99): Find or create a better domain name to test this with.
+       * This is just the first one I found with a hyphen. */
+      const target = 'network-tools.com';
```
Comment (merlinnot) [inline packages/grpc-js/test/test-resolver.ts]:
```suggestion
      const target = 'google-analytics.com';
```
