### PR TITLE
grpc-js-xds: Add more missing files, add distrib test

### LINKED ISSUE #2020: No such Type or Enum 'type.matcher.v3.NodeMatcher'
### Problem description

I receive "no such Type or Enum 'type.matcher.v3.NodeMatcher' in Type .envoy.service.status.v3.ClientStatusRequest" error when trying to run my application.

There is `./node_modules/@grpc/grpc-js-xds/deps/envoy-api/envoy/type/matcher/v3/node.proto` with `type.matcher.v3.NodeMatcher` type, but I don't understand why it can't find it. 

### Reproduction steps

1. Install grpc-js-xds as a dependency to a project
2. Load grpc-js-xds with require `require('@grpc/grpc-js-xds');`

### Environment
 - OS name, version and architecture: Mac OS Big Sur 11.6
 - Node version 15.10.0
 - Node installation method nvm
 - Package name and version grpc-js-xds@1.5.1

### Additional context
Stack trace

```
Error: no such Type or Enum 'type.matcher.v3.NodeMatcher' in Type .envoy.service.status.v3.ClientStatusRequest
    at Type.lookupTypeOrEnum (<project-path>/node_modules/protobufjs/src/namespace.js:411:15)
    at Field.resolve (<project-path>/node_modules/protobufjs/src/field.js:268:94)
    at Type.resolveAll (<project-path>/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Root.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Root.resolveAll (<project-path>/node_modules/protobufjs/src/root.js:258:43)
    at Object.loadProtosWithOptionsSync (<project-path>/node_modules/@grpc/proto-loader/build/src/util.js:67:16)
    at Object.loadSync (<project-path>/node_modules/@grpc/proto-loader/build/src/index.js:194:31)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/csds.js:182:36)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/xds-client.js:30:16)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/resolver-xds.js:20:22)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/index.js:20:22)
```

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #2020, and the distrib test should stop this kind of thing from happening in the future.

### CODE REVIEW

File: test/distrib/distrib-test.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ */
+
+const grpcJs = require('@grpc/grpc-js');
+
+const grpcJsXds = require('@grpc/grpc-js-xds');
+
+const protoLoader = require('@grpc/proto-loader');
```
Comment (stanley-cheung) [inline test/distrib/distrib-test.js:22]: nit: newline?

File: test/distrib/run-distrib-test.sh [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+# limitations under the License.
+
+set -ex
+
+cd $(dirname $0)
+base=$(pwd)
+
+cd ../../packages/grpc-js
+npm pack
+cd ../grpc-js-xds
```
Comment (stanley-cheung) [inline test/distrib/run-distrib-test.sh:23]: just to double check, should that be `../../packages/grpc-js-xds`?

File: test/distrib/run-distrib-test.sh [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+npm pack
+cd ../proto-loader
```
Comment (stanley-cheung) [inline test/distrib/run-distrib-test.sh:25]: ditto

**Review by stanley-cheung — APPROVED** [review]
LGTM except for one question

File: test/distrib/run-distrib-test.sh (hunk 2 above)
Comment (stanley-cheung) [reply test/distrib/run-distrib-test.sh:23]: oh nevermind. It's not coming from `pwd`. Nevermind. What you have is correct.
